version: "3.9"
services:
  portada:
    build: ./portada
    ports:
      - "8081:80"  # Portada

  crud:
    build: ./crud
    ports:
      - "8082:80"  # CRUD

  redes-sociales:
    build: ./redes-sociales
    ports:
      - "8083:80"  # Redes sociales

  proxy:
    image: nginx:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html  # Asegúrate de que el archivo HTML esté correctamente copiado
      - ./nginx.conf:/etc/nginx/nginx.conf  # Archivo de configuración de Nginx
    ports:
      - "8080:80"  # Nginx escuchando en el puerto 8080
    depends_on:
      - portada
      - crud
      - redes-sociales
